const ACTIONS = {
  CREATE_MESSAGE_REQUEST: "CREATE_MESSAGE_REQUEST",
  CREATE_MESSAGE_SUCCESS: "CREATE_MESSAGE_SUCCESS",
  CREATE_MESSAGE_ERROR: "CREATE_MESSAGE_ERROR",

  GET_MESSAGES_REQUEST: "GET_MESSAGES_REQUEST",
  GET_MESSAGES_SUCCESS: "GET_MESSAGES_SUCCESS",
  GET_MESSAGES_ERROR: "GET_MESSAGES_ERROR",
};
export default ACTIONS;
